# SPDX-FileCopyrightText: 2025 Pavol Babinčák
# SPDX-License-Identifier: MIT

FROM docker.io/ubuntu:24.04

ENV DEBIAN_FRONTEND=noninteractive
ENV TERM=xterm

RUN apt-get update

# Ubuntu in container:
RUN apt-get -y install \
    libcap2-bin

# Cursor start:
RUN apt-get -y install \
    zsh \
    fuse \
    libfuse2 \
    libglib2.0-0 \
    libnss3 \
    libdbus-1-3 \
    libatk1.0-0 \
    libatk-bridge2.0-0 \
    libcups2 \
    libdrm2 \
    libgtk-3-0 \
    libgbm1 \
    libasound2t64

# Cursor does not complain
RUN apt-get -y install \
    libcanberra-gtk3-module \
    packagekit-gtk3-module \
    git


RUN apt-get -y install \
    libxkbfile-dev

# npx and so on
RUN apt install -y \
    npm

# npm ERR! Tracker "idealTree" already exists
WORKDIR /tmp
RUN npm install @playwright/test@latest
RUN npx playwright install-deps

# Playwright deps
#RUN npx playwright install

# Install browsers
RUN apt-get -y install \
    firefox

RUN apt-get install -y curl && \
    mkdir -p /etc/apt/keyrings && \
    curl https://dl.google.com/linux/linux_signing_key.pub | gpg --dearmor > /etc/apt/keyrings/google-chrome.gpg && \
    echo "deb [arch=amd64 signed-by=/etc/apt/keyrings/google-chrome.gpg] http://dl.google.com/linux/chrome/deb/ stable main" > /etc/apt/sources.list.d/google-chrome.list && \
    apt-get update && \
    apt-get install -y google-chrome-stable
#RUN apt-get -y install \
#    libx11-dev \
#    libsecret-1-dev \
#    libxss1 \
#    libnss3 \
#    libgtk-3-dev \
#    xvfb

# [main 2025-01-31T17:08:10.901Z] vscode-file: Refused to load resource /tmp/.mount_cursorg7756E/resources/app/extensions/theme-seti/icons/seti.woff from vscode-file: protocol (original URL: vscode-file://vscode-app/tmp/.mount_cursorg7756E/resources/app/extensions/theme-seti/icons/seti.woff)
#RUN apt install -y \
#    fonts-dejavu \
#    fontconfig \
#    libfontconfig1 \
#    libfreetype6 \
#    ttf-mscorefonts-installer \
#    fonts-liberation \
#    fonts-liberation2 \
#    fonts-noto
#RUN fc-cache -f -v

# RUN apt-get clean
