# SPDX-License-Identifier: CC0-1.0
# SPDX-FileCopyrightText: 2025 Pavol Babinčák

useTabs: true
singleQuote: true
trailingComma: "none"
printWidth: 100
plugins:
  - prettier-plugin-svelte
  - prettier-plugin-tailwindcss
overrides:
  - files: "*.svelte"
    options:
      parser: svelte
